export const ACTIONS = {
    CREATE_CARDSET:'CREATE_CARDSET',
    SHUFFLE_CARDS:'SHUFFLE_CARDS',
    ACTIVATE_CARD: 'ACTIVATE_CARD',
    DEACTIVATE_CARDS:'DEACTIVATE_CARDS',

    UP_SMALL_COUNTER:'UP_SMALL_COUNTER',
    ZERO_SMALL_COUNTER:'ZERO_SMALL_COUNTER',
    SET_BIG_COUNTER:'SET_BIG_COUNTER',
    OPEN_CARDS: 'OPEN_CARDS',

    START_TIMER:'START_TIMER'

}